# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: Job1
      steps: 
      - bash: echo Build stage
    - job: job2 
      steps:
        - bash: echo second Build job
  - stage: DevDeploy
    dependsOn: Build
    jobs:
    - job: DevDeployJob
      steps: 
      - bash: echo DevJob
    - job: Dev2Job 
      steps:
        - bash: echo second Devjob
  - stage: QAJob
    dependsOn: Build
    jobs:
    - job: QAFirstJob
      steps: 
      - bash: echo QA First stage
    - job: QAJob2 
      steps:
        - bash: echo second QA job            
  - stage: ProdJob
    dependsOn: 
     - DevDeploy
     - QAJob
    jobs:
    - job: ProdJob
      steps: 
      - bash: echo Prod Job

    


